name: E2E

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: npx playwright test

            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
